### ISSUE TITLE
main.m not executable

### ISSUE THREAD

**Issue by fabian-s** [wk45/PPD#1]
(.. sorry if these are stupid, I use MATLAB very rarely.)

I can't get the example script to run (Linux; Matlab R2024a Update 4 (24.1.0.2628055) 64-bit (glnxa64))

1.  I see

```
>> run("../main.m")
Incorrect number or types of inputs or outputs for function findMaxLam.

Error in main (line 20)
    maxlam = findMaxLam(t, f, maxVal, n_grid, 'parallel', true);

Error in run (line 112)
evalin('caller', strcat(scriptStem, ';'));
``` 

2. If I try to call that function directly without the optional argument, it makes it past the argument-parser at least, but then it doesn't find your mex-function:

```
>> maxlam = findMaxLam(t, f, maxVal, n_grid) 
Running in sequential mode
Unrecognized function or variable 'DynamicProgrammingQ_Adam'.

Error in mainWarpingWrapper (line 34)
        gam0 = DynamicProgrammingQ_Adam(q_c/norm(q_c),mq_c/norm(mq_c),lam,0)';

Error in findMaxLam (line 27)
            fns = mainWarpingWrapper(t,f',lam_rough(i));
 ```

Since compiled mex files are platform-specific, maybe you need to make the source files for them available as well so users can compile them to the right format on their own machines? 

I would appreciate any pointers to help me run this on our machines, thank you for sharing your code!

**Comment by fabian-s** [comment]
@wk45 

after some more research I'm pretty sure issue 2 is due to the precompiled DynamicProgrammingQ_Adam MEX files being for Windows and MacOS, respectively. 
Could you also share a "XXXX.mexa64" version precompiled for Linux, or the source files so I can compile it myself?

**Comment by wk45** [comment]
@fabian-s 

Thank you for your understanding. Since I don't have access to a Linux system, I've uploaded the `DynamicProgrammingQ_Adam.c` file. You can easily compile it using MATLAB's `mex` function by entering the following command in MATLAB:

```matlab
mex DynamicProgrammingQ_Adam.c
```

**Comment by fabian-s** [comment]
Thank you so much, this works now. 

Do you have any tips how  to avoid the other error 
```
Incorrect number or types of inputs or outputs for function findMaxLam.

Error in main (line 20)
    maxlam = findMaxLam(t, f, maxVal, n_grid, 'parallel', true);
``` 
?

**Comment by wk45** [comment]
@fabian-s 

I attempted to investigate this problem, but it functions correctly on my local machine. I believe it may be due to version issues with Matlab; I am currently using Matlab 2024a. The only suggestion I have for now is regarding the output of the function `mainWarpingWrapper` used in `findMaxLam` function. Since it returns three outputs, it might be more appropriate to write 

```Matlab
[fns, ~, ~] = mainWarpingWrapper(t,f',lam_rough(i));
```
instead of `fns = mainWarpingWrapper(t,f',lam_rough(i));`. Here, ~ indicates that the corresponding outputs are being ignored.
